export const PHASE1_PLAYER_STARTING_AGE = 14;
export const PHASE1_STARTING_WALLET_BALANCE = 150;
export const PHASE1_TRAINING_COST = 20;
export const PHASE1_TRAINING_GAIN = 2;
export const PHASE1_TRYOUT_COST = 35;
export const PHASE1_TRYOUT_REQUIRED_SCORE = 130;
